#访问服务器文件资源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  application:
    name: home
  web:
    resources:
      static-locations: file:C://images
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

server:
  port: 8866
